### ISSUE TITLE
dynamically linking externals (using Pd)

### ISSUE THREAD

**Issue by umlaeute** [grrrr/flext#12]
it seems that i cannot properly link against the dynamic library of flext.

My rough `Makefile` (i've used `make install DESTDIR=/tmp/flex` for pseudo-installing flext):

``` Makefile
FLEXTDIR=/tmp/flex/usr/local/
CXXFLAGS=-DPD -I$(FLEXTDIR)/include/flext -I/usr/include/pd -fPIC -DPIC
LDFLAGS=-rdynamic -shared -Wl,-rpath,"\$ORIGIN",--enable-new-dtags -fPIC
LIBS=$(LDFLAGS) -L$(FLEXTDIR)/lib -lflext-pd_d

henon.pd_linux: henon.o
    g++ -o $@ $< $(CXXFLAGS) $(LIBS)

henon.o: henon.cpp
    g++ -o $@ -c $< $(CXXFLAGS)
```

this gives me a nice `henon.pd_linux`.
But when I run it, it cannot be loaded with the error

> ./henon.pd_linux: ./henon.pd_linux: undefined symbol: _ZN17flext_base_single4InitEv

which translates to `flext_base_single::Init()` not being found.

everything works fine when i link against the static version of flext `-lflext-pd_s`

**Comment by umlaeute** [comment]
ah, it seems that for dynamic linking, I have to:
- define `FLEXT_SHARED` in the CPPFLAGS
- link against `-lflext-pd` _only_ (no idea what _libflext-pd-d_ is for; linking against both crashes Pd during init)

**Comment by grrrr** [comment]
Exactly right.  libflext-pd_d is the debug version.

**Comment by grrrr** [comment]
Btw., flext can now also be used without linking, by using -D FLEXT_INLINE, where all needed code will be inlined to the external.

**Comment by umlaeute** [comment]
ah thanks for clarification about the `_d` suffix.

`-DFLEXT_INLINE` doesn't work for me, as the `.cpp` files are not installed with `make install`

**Comment by grrrr** [comment]
Seems you are working with the autoconf files. It's a wonder they work at all ;-)
I will have a look and include the .cpp files to the installation.

**Comment by grrrr** [comment]
Ok, i believe to have fixed the installation of the .cpp files both for the flext build system and autoconf.

**Comment by grrrr** [comment]
I think all points are clarified, closing the issue.
