### ISSUE TITLE
automake 'foreign'

### ISSUE THREAD

**Issue by umlaeute** [grrrr/flext#23]
when initializing automake, the `foreign` option should be passed (since a number of files (e.g. README) required to be strictly GNU autotools conformant) are missing.

e.g. configure.ac:10

     AM_INIT_AUTOMAKE([foreign])

this is needed to bootstrap the project with the standard `autoreconf -fiv` (instead of `./bootstrap.h` which adds the `--foreign` manually)

**Comment by grrrr** [comment]
Hi Iohannes, could you file a pull request?
thanks, Thomas
