### ISSUE TITLE
link broken for max/msp sdk

### ISSUE THREAD

**Issue by porres** [grrrr/flext#27]
these links are broken 

    for Windows (http://synthesisters.com/pluggo3/downloadMaxWinSDK.php)
    for OSX (http://www.synthesisters.com/sdk/max.php)

here's where it seems to live now https://cycling74.com/downloads/sdk

**Comment by porres** [comment]
Moreover, do I need them if I want to compile just a Pd external? Say, constantq~ for windows?

**Comment by grrrr** [comment]
Thanks, that's fixed. You don't need the Max part for Pd.
