### ISSUE TITLE
building failed

### ISSUE THREAD

**Issue by porres** [grrrr/flext#28]
Hi, so I'm trying to build and install flext.

at step 1.2 "Building and installing flext" I entered "bash build.sh pd gcc" into the terminal, then "buildsys/config-mac-max-gcc.txt" was created and I edited it to refer to the new Pd Vanilla's path, so all I did was, instead of Pd-042-5 including "PDPATH=/Applications/Pd-0.47-1-64bit.app/Contents/Resources"

then I tried building it again and got three errors, here's everything...

--------------

-------------------------------------------------------------------------
A default package configuration file has been created.
Please edit config.txt, then start again.
-------------------------------------------------------------------------
make: *** [config.txt] Error 1
Alexandres-MacBook-Pro:flext-master porres$ bash build.sh pd gcc
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f ./buildsys/gnumake-sub.mak  PLATFORM=mac RTSYS=pd COMPILER=gcc BUILDPATH=./buildsys/ PKGINFO=package.txt BUILDCLASS=flext USRCONFIG=config.txt USRMAKE=build/gnumake-mac-gcc.inc TARGETMODE=release TARGETTYPE=single _build_
buildsys/mac/gnumake-gcc-targets.inc:22: warning: overriding commands for target `pd-darwin/release-single'
buildsys/mac/gnumake-gcc-targets.inc:18: warning: ignoring old commands for target `pd-darwin/release-single'
mkdir -p pd-darwin/release-single
mkdir -p pd-darwin/release-single/
c++ -c -ffast-math -mmacosx-version-min=10.6  -O3 -mtune=native  -DFLEXT_USE_SIMD -DNDEBUG -DFLEXT_EXPORTS -DFLEXT_SYS=2 -DPD -I/Applications/Pd-0.47-1-64bit.app/Contents/Resources/src -I/Applications/Pd-0.47-1-64bit.app/Contents/Resources/include -I/Applications/Pd-0.47-1-64bit.app/Contents/Resources/include/pd source/flext.h -o pd-darwin/release-single/flext.h.gch
clang: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
In file included from source/flext.h:60:
In file included from source/flclass.h:18:
In file included from source/flbase.h:19:
source/flsupport.h:130:1: warning: replacement function 'operator new' cannot be
      declared 'inline' [-Winline-new-delete]
inline void *operator new(size_t bytes) NEWTHROW { return flext_root::op...
^
source/flsupport.h:131:1: warning: replacement function 'operator delete' cannot
      be declared 'inline' [-Winline-new-delete]
inline void operator delete(void *blk) DELTHROW { flext_root::operator d...
^
source/flsupport.h:133:1: warning: replacement function 'operator new[]' cannot
      be declared 'inline' [-Winline-new-delete]
inline void *operator new[](size_t bytes) NEWTHROW { return flext_root::...
^
source/flsupport.h:134:1: warning: replacement function 'operator delete[]'
      cannot be declared 'inline' [-Winline-new-delete]
inline void operator delete[](void *blk) DELTHROW { flext_root::operato...
^
source/flsupport.h:236:53: error: assigning to 't_float' (aka 'float') from
      incompatible type 't_word' (aka 'word')
                        Element(FLEXT_ARRAYTYPE s) { FLEXT_GETSAMPLE(el) = s; }
                                                                         ^ ~
source/flsupport.h:237:42: error: non-const lvalue reference to type 't_word'
      (aka 'word') cannot bind to a value of unrelated type 't_float'
      (aka 'float')
  ...operator FLEXT_ARRAYTYPE &() { return FLEXT_GETSAMPLE(el); }
                                           ^~~~~~~~~~~~~~~~~~~
source/flsupport.h:219:43: note: expanded from macro 'FLEXT_GETSAMPLE'
#               define FLEXT_GETSAMPLE(x) ((x).w_float)
                                          ^~~~~~~~~~~~~
source/flsupport.h:238:47: error: no viable conversion from returned value of
      type 'const t_float' (aka 'const float') to function return type 't_word'
      (aka 'word')
  ...operator FLEXT_ARRAYTYPE () const { return FLEXT_GETSAMPLE(el); }
                                                ^~~~~~~~~~~~~~~~~~~
source/flsupport.h:219:43: note: expanded from macro 'FLEXT_GETSAMPLE'
#               define FLEXT_GETSAMPLE(x) ((x).w_float)
                                          ^~~~~~~~~~~~~
/Applications/Pd-0.47-1-64bit.app/Contents/Resources/src/m_pd.h:151:15: note: 
      candidate constructor (the implicit copy constructor) not viable: no known
      conversion from 'const t_float' (aka 'const float') to 'const word &' for
      1st argument
typedef union word
              ^
4 warnings and 3 errors generated.
make[1]: *** [pd-darwin/release-single/flext.h.gch] Error 1
make: *** [build-release-single] Error 2
Alexandres-MacBook-Pro:flext-master porres$

**Comment by porres** [comment]
I thought that maybe it was the new vanilla, but I downloaded the old 0.42-5, did nothing to edit the "buildsys/config-mac-max-gcc.txt" files, and still got the same errors...

**Comment by grrrr** [comment]
Hi, the Pd version can be the latest. Which compiler are you using? Lately, i have only used clang.

**Comment by grrrr** [comment]
For the records, your version:
g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by porres** [comment]
clang-802.0.42 ;)

**Comment by grrrr** [comment]
Should be fixed with commit f079045d2340ade5d23b8625733e1b8bf1e58881

**Comment by porres** [comment]
thanks!
