### ISSUE TITLE
Mac OS ARM build not working

### ISSUE THREAD

**Issue by josmithiii** [grrrr/flext#52]
Here is what I see:

</c/flext> sh build.sh pd gcc build
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f ./buildsys/gnumake-sub.mak  PLATFORM=mac RTSYS=pd COMPILER=gcc BUILDPATH=./buildsys/ PKGINFO=package.txt BUILDCLASS=flext USRCONFIG=config.txt USRMAKE=build/gnumake-mac-gcc.inc TARGETMODE=release TARGETTYPE=single _build_
buildsys/mac/gnumake-gcc-targets.inc:22: warning: overriding commands for target `pd-darwin/release-single'
buildsys/mac/gnumake-gcc-targets.inc:18: warning: ignoring old commands for target `pd-darwin/release-single'
mkdir -p ./
c++ -c -I/opt/local/include -ffast-math -mmacosx-version-min=10.9  -O3 -mtune=native  -I/opt/local/include -std=c++11 -fvisibility-inlines-hidden -arch i386    -DFLEXT_USE_SIMD -DNDEBUG -DFLEXT_EXPORTS -DFLEXT_SYS=2 -DPD -I pd-darwin/release-single -I/Applications/jos/Pd-0.52-2.app/Contents/Resources/src -I/Applications/jos/Pd-0.52-2.app/Contents/Resources/include -I/Applications/jos/Pd-0.52-2.app/Contents/Resources/include/pd source/flbase.cpp -o pd-darwin/release-single/flbase.opp_i386
**error: unknown target CPU 'apple-a12'**
note: valid target CPU values are: i386, i486, winchip-c6, winchip2, c3, i586, pentium, pentium-mmx, pentiumpro, i686, pentium2, pentium3, pentium3m, pentium-m, c3-2, yonah, pentium4, pentium4m, prescott, nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, rocketlake, icelake-server, tigerlake, sapphirerapids, alderlake, knl, knm, lakemont, k6, k6-2, k6-3, athlon, athlon-tbird, athlon-xp, athlon-mp, athlon-4, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, znver3, x86-64, geode
make[1]: *** [pd-darwin/release-single/flbase.opp_i386] Error 1
make: *** [build-release-single] Error 2

**Comment by grrrr** [comment]
There is a mismatch between `-arch i386` and `-mtune native`. You need to leave away either one of those.
Do you want to compile for your own machine, or do a cross-compile for i386?
The settings are made in `flext/buildsys/config-mac-pd-gcc.txt`.

**Comment by josmithiii** [comment]
Thank you!  It's compiling now after the following change where you note:
```
# cross-compilation (optional)
# JOS: ARCH=i386 x86_64 # ppc ppc64
ARCH=arm64
```
