### ISSUE TITLE
how to deal with Pd64 (double precision) externals?

### ISSUE THREAD

**Issue by umlaeute** [grrrr/flext#54]
this is more of a question than an issue:

when building flext as a *dynamic* library, you get something like `libflext-pd.so` against which  flext-externals link.

however, afaiu `libflext-pd.so` will not be able to deal with multiple floatsizes (either it can handle Pd32 (single precision) or Pd64 (double precision); but not both).

so how should this be handled?

my naive suggestion would be:
| RTE | flext dylib | 
|---|---|
| Pd32 | `libflext-pd.so`  |
| Pd64 | `libflext-pd64.so`  |

but maybe you have better ideas...

**Comment by grrrr** [comment]
Has the discussion on the pd executable name settled in this respect? If it is pd64 for double-precision, your suggestion would be totally adequate.

**Comment by umlaeute** [comment]
fair enough. i've taken this [to the committee](https://lists.puredata.info/pipermail/pd-dev/2023-07/023444.html)

**Comment by umlaeute** [comment]
@millerpuckette has spoken:
> I think pd64 is fine - however, it would be wise when distributing it to emphasize that it's 64 bit samples, not 64 bit architecture. 

since the actual name of the flext dylib is an implementation detail, i don't think that the "however" applies.

**Comment by umlaeute** [comment]
I've update my PR #53 to include fixes for building with double precision

**Comment by grrrr** [comment]
Ok, i think we have resolved that one.

**Comment by umlaeute** [comment]
for whatever reason my PR was incomplete and the Pd64 related fixes were missing.
(i cannot re-open)
