### ISSUE TITLE
`-framework veclib` should be `-framework Accelerate`

### ISSUE THREAD

**Issue by ssfrr** [grrrr/flext#8]
On Yosemite, both for PD and Max builds I was getting the error:

```
ld: framework not found vecLib
```

It looks like that name has been deprecated for some time and now doesn't work any more. Just changing `vecLib` to `Accelerate` in buildsys/mac/gnumake-gcc.inc got me building again.

**Comment by grrrr** [comment]
I hope to have fixed this.
